### ISSUE TITLE
TypeError: context.factory.updateIdentifier is not a function

### ISSUE THREAD

**Issue by LuisUrrutia** [ThomZz/ts-jest-mock-import-meta#4]
I got this error using it with `formatjs/ts-transformer`

```
TypeError: context.factory.updateIdentifier is not a function

      at visitEachChildOfIdentifier (../../node_modules/typescript/lib/typescript.js:91548:36)
      at Object.visitEachChild (../../node_modules/typescript/lib/typescript.js:91541:42)
      at c (../../node_modules/ts-jest-mock-import-meta/dist/index.min.js:1:681)
      at visitNode (../../node_modules/typescript/lib/typescript.js:91309:23)
      at visitEachChildOfImportSpecifier (../../node_modules/typescript/lib/typescript.js:91895:139)
      at Object.visitEachChild (../../node_modules/typescript/lib/typescript.js:91541:42)
      at c (../../node_modules/ts-jest-mock-import-meta/dist/index.min.js:1:681)
      at visitArrayWorker (../../node_modules/typescript/lib/typescript.js:91397:48)
      at visitNodes (../../node_modules/typescript/lib/typescript.js:91361:23)
      at visitEachChildOfNamedImports (../../node_modules/typescript/lib/typescript.js:91892:61)
      at Object.visitEachChild (../../node_modules/typescript/lib/typescript.js:91541:42)
      at c (../../node_modules/ts-jest-mock-import-meta/dist/index.min.js:1:681)
      at visitNode (../../node_modules/typescript/lib/typescript.js:91309:23)
      at visitEachChildOfImportClause (../../node_modules/typescript/lib/typescript.js:91883:128)
      at Object.visitEachChild (../../node_modules/typescript/lib/typescript.js:91541:42)
      at c (../../node_modules/ts-jest-mock-import-meta/dist/index.min.js:1:681)
      at visitNode (../../node_modules/typescript/lib/typescript.js:91309:23)
      at visitEachChildOfImportDeclaration (../../node_modules/typescript/lib/typescript.js:91874:120)
      at Object.visitEachChild (../../node_modules/typescript/lib/typescript.js:91541:42)
      at c (../../node_modules/ts-jest-mock-import-meta/dist/index.min.js:1:681)
      at visitArrayWorker (../../node_modules/typescript/lib/typescript.js:91397:48)
      at visitNodes (../../node_modules/typescript/lib/typescript.js:91361:23)
      at visitLexicalEnvironment (../../node_modules/typescript/lib/typescript.js:91427:22)
      at visitEachChildOfSourceFile (../../node_modules/typescript/lib/typescript.js:91970:59)
      at Object.visitEachChild (../../node_modules/typescript/lib/typescript.js:91541:42)
      at c (../../node_modules/ts-jest-mock-import-meta/dist/index.min.js:1:681)
      at Object.visitNode (../../node_modules/typescript/lib/typescript.js:91309:23)
      at ../../node_modules/ts-jest-mock-import-meta/dist/index.min.js:1:731
      at transformSourceFileOrBundle (node_modules/typescript/lib/typescript.js:87256:51)
      at transformation (node_modules/typescript/lib/typescript.js:108883:16)
      at transformRoot (node_modules/typescript/lib/typescript.js:108906:73)
      at transformNodes (node_modules/typescript/lib/typescript.js:108891:72)
      at emitJsFileOrBundle (node_modules/typescript/lib/typescript.js:109478:26)
      at emitSourceFileOrBundle (node_modules/typescript/lib/typescript.js:109413:7)
      at forEachEmittedFile (node_modules/typescript/lib/typescript.js:109167:26)
      at emitFiles (node_modules/typescript/lib/typescript.js:109387:5)
      at emitWorker (node_modules/typescript/lib/typescript.js:116758:26)
      at node_modules/typescript/lib/typescript.js:116743:53
      at runWithCancellationToken (node_modules/typescript/lib/typescript.js:116832:16)
      at Object.emit (node_modules/typescript/lib/typescript.js:116743:22)
      at getFileEmitOutput (node_modules/typescript/lib/typescript.js:119105:50)
      at Object.getEmitOutput (node_modules/typescript/lib/typescript.js:133557:14)
      at TsCompiler.getCompiledOutput (../../node_modules/ts-jest/dist/legacy/compiler/ts-compiler.js:142:48)
      at TsJestCompiler.getCompiledOutput (../../node_modules/ts-jest/dist/legacy/compiler/ts-jest-compiler.js:14:39)
      at TsJestTransformer.exports.TsJestTransformer.TsJestTransformer.processWithTs (../../node_modules/ts-jest/dist/legacy/ts-jest-transformer.js:265:37)
      at TsJestTransformer.exports.TsJestTransformer.TsJestTransformer.process (../../node_modules/ts-jest/dist/legacy/ts-jest-transformer.js:188:24)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:723:19)
```

My config is:
```js
const tsJestConfig = [
  'ts-jest',
  {
    tsconfig: '<rootDir>/tsconfig.json',
    // https://github.com/ThomZz/ts-jest-mock-import-meta
    diagnostics: {
      ignoreCodes: [1343]
    },
    astTransformers: {
      before: [
        {
          path: 'ts-jest-mock-import-meta',
          options: { metaObjectReplacement: { env: {} } }
        },
        {
          path: '@formatjs/ts-transformer/ts-jest-integration',
          options: { overrideIdFn: '[sha512:contenthash:base64:6]', ast: true }
        }
      ]
    }
  }
];
```

**Comment by ThomZz** [comment]
Possibily linked to the typescript version and the ts-jest version combination.
Wich version of typescript and ts-jest are you currently using ?

**Comment by LuisUrrutia** [comment]
This are the versions I'm using.

"ts-jest": "^29.1.0",
"typescript": "^4.9.4"

**Comment by ThomZz** [comment]
Seems good to me. Does it work if you remove the transformer "@formatjs/ts-transformer/ts-jest-integration" ?

**Comment by ThomZz** [comment]
@LuisUrrutia any updates ?

Issue will soon be closed if no follow-up is received.
